# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: install

    - task: Npm@1
      displayName: 'npm build'
      inputs:
        command: custom
        customCommand: run-script build
        

    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: 'build'
        TargetFolder: '$(build.artifactstagingdirectory)'
        CleanTargetFolder: true

    - task: PublishBuildArtifacts@1      
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'build'

- stage: deploy
  jobs:
  - deployment: deploy
    pool:
      vmImage: 'windows-latest'
    variables:
      storageaccountname: joseprodstorage
    environment: 'Deploy to Storage Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: build
            
          - task: AzureFileCopy@3
            inputs:
              sourcePath: $(Pipeline.Workspace)/build
              azureSubscription: 'JoseResourceManagerSubscription'
              destination: azureBlob
              storage: $(storageaccountname)
              containerName: "$web"